language: node_js
node_js:
  - "10.16.3"
dist: xenial
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
script:
- npm install
- ng lint
- ng build --prod --aot
